#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - '12'

#运行的脚本命令
script:
  - npm run lint:travis
  - npm run test:unit
  - codecov ./test/unit/coverage/clover.xml


#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
    - develop
